name: Test
on:
  pull_request:
    paths: ['go/excellent/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: go test go/excellent/*.go
